services:
  node:
    container_name: node
    build: ./
    restart: always
    env_file:
      - .env
    ports:
      - 3000:3000
  
  nginx:
    container_name: nginx_app
    build: ./
    restart: always
    ports:
      - 80:80
      - 443:443
    depends_on: 
      - node