version: '1.0'

services:
  backend:
    container_name: discordia-backend
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    env_file:
      - .env
    ports:
      - '3000:3000'
    environment:
      - NODE_ENV=production
    networks:
      - discordia-net

networks:
  discordia-net:
    driver: bridge
